@startuml

database 서울열린데이터광장 as db <<Actor>>
card 파이어베이스 as fb <<Actor>>
card 카카오톡  as kt <<Actor>>
actor :사용자: as User
actor :비회원: as nUser
actor :회원: as yUser

User <|-down- nUser
User <|-- yUser

rectangle "열차 시간표 조회" {
    User -right-> (시간표 검색)
    (시간표 검색) -right-> db
}

rectangle SNS {
    nUser --> (회원가입)
    yUser --> (로그인)
    yUser --> (비밀번호 재설정)
    (로그인) <.. (게시물 검색) : <<include>>
    (로그인) <.. (게시물 조회) : <<include>>
    (로그인) <.. (프로필 설정) : <<include>>
    (로그인) <.. (다른 사용자 \n프로필 조회) : <<include>>

    (프로필 설정) <|-- (이름 설정)
    (프로필 설정) <|-- (프로필 사진\n설정)
    (프로필 설정) <|-- (프로필 배경\n설정)
    (프로필 설정) --> (사용자의 게시물\n조회)

    (다른 사용자 \n프로필 조회) <|-- (이름 조회)
    (다른 사용자 \n프로필 조회) <|-- (프로필 사진\n조회)
    (다른 사용자 \n프로필 조회) <|-- (프로필 배경\n조회)
    (다른 사용자 \n프로필 조회) --> (사용자의 게시물\n조회)

    (이름 설정) <.. (게시물 업로드) : <<include>>
    (게시물 업로드) <.. (사진 게시) : <<extends>>

    (게시물 조회) --> (게시물 설정)
    (게시물 조회) --> (좋아요 누르기)
    (게시물 조회) --> (댓글 조회)
    (게시물 조회) --> (카카오톡 공유)

    (게시물 검색) <|-- (제목 검색)
    (게시물 검색) <|-- (본문 검색)

    (게시물 설정) <|-- (게시물 수정)
    (게시물 설정) <|-- (게시물 삭제)

    (댓글 조회) --> (댓글 삭제)
    (댓글 조회) --> (댓글 달기)
}

(카카오톡 공유) -u-> kt
SNS --> fb

@enduml