@startuml
FragmentPasswordReset -> View.OnClickListener
FragmentPasswordReset --> onCompleteListener
class FragmentPasswordReset {
    -mAuth : FirebaseAuth
    fragmentManager : FragmentManager
    et_email : EditText
    btn_send : Button

    +onCreateView(inflater,container, savedInstanceState) : View
    +onStart() : void
    +onClick(v) : void
    -send() : void
    +onComplete(task) : void
    -startToast(msg) : void
}

interface  View.OnClickListener {
    +onClick(v) : void
}
interface onCompleteListener {
    +onComplete(task) : void
}
@enduml