@startuml
FragmentPasswordReset -> View.OnClickListener
FragmentPasswordReset --> FirebaseAuth.sendPasswordResetEmail.addOnCompleteListener
class FragmentPasswordReset {
    -mAuth : FirebaseAuth
    fragmentManager : FragmentManager
    et_email : EditText
    btn_send : Button

    +onCreateView(inflater,container, savedInstanceState) : View
    +onStart() : void
    +onClick(v) : void
    -send() : void
    +onComplete(task) : void
    -startToast(msg) : void
}

interface  View.OnClickListener {
    +onClick(v) : void
}
namespace FirebaseAuth.sendPasswordResetEmail{
    abstract class addOnCompleteListener {
        +onComplete(task) : void
    }
}
@enduml