@startuml
MainActivity -> OnBackPressedCallback
MainActivity --> NavigationBarView.OnItemSelectedListener
MainActivity --> DialogInterface.OnClickListener

abstract class OnBackPressedCallback {
    +handleOnBackPressed() : void
}
class MainActivity {
    bottomNavigationView : BottomNavigationView
    -chart : FragmentChart
    -sns : FragmentSNSLobby
    -fragmentManager : FragmentManager
    -isChart : boolean

    #onCreate(savedInstanceState) : void
    #onStart() : void
    +onNavigationItemSelected(item) : boolean
    +handleOnBackPressed() : void
    +onClick(dialog, which) : void
    +showDialog(context) : void
    -switchSns() : void
    -switchChart() : void
}

interface NavigationBarView.OnItemSelectedListener {
    +onNavigationItemSelected(item) : boolean
}
interface DialogInterface.OnClickListener {
    +onClick(dialog, which) : void
}

@enduml